### ISSUE TITLE
Should this repo (or org) host ACT/FFXIV docs

### ISSUE THREAD

**Issue by quisquous** [OverlayPlugin/OverlayPlugin#108]
Techno (who ignored the invite to this repo and so I can't @ them) asked me about various docs that are floating around.  This is mostly stuff pinned in ACT discords that are owned by ngld or other people (who also aren't around).  I think it'd make sense to consolidate this stuff ... somewhere? where there are multiple owners.

I'm asking here mostly because there's not a lot of other shared space to have this conversation, and some of the options include this repo and org.  These docs include:
* https://gist.github.com/ngld/e2217563bbbe1750c0917217f136687d
* https://github.com/FFXIV-ACT/setup-guide#readme

Possible options include:
1) Add these docs to this repo
2) Create a new repo (e.g. OverlayPlugin/guides or OverlayPlugin/docs or OverlayPlugin/ACT_FFXIV) and add docs to that repo
3) Create a new org and repo (e.g. ACT_FFXIV)

These docs are sort of out of place here (given that they're kind of aimed at "general FFXIV plugin setup), but simultaneously they already include a lot of stuff about overlays and OverlayPlugin, and so I think they could be a good fit too.

**Comment by panicstevenson** [comment]
3 makes the most sense to me if there was a plan to ever host the plugin inside of that repo; however, I think OverlayPlugin/docs is also fine

**Comment by xpdota** [comment]
My thoughts are that documentation should live as close to the project that it is relevant to as possible. OP docs should be in OP, general XIV/ACT guides in either the ACT_FFXIV repo/org, and so on.

My main concern is not having another issue like the log guide, where it's intertwined with one project, but is *used as* the general guide because it's effectively just documenting the ACT plugin. So I'd rather err on the side of "keep the docs in the repo of the thing they're documenting".

**Comment by valarnin** [comment]
I think that from my perspective, documentation should live based on the writers/maintainers rather than on the subject. That's why it previously made sense to keep e.g. cactbot's `LogGuide.md` in cactbot, because the primary maintainers/writers of the documentation were also primarily contributing to that repo. (I think that line has blurred a bit and maybe that's a conversation to have later on after seeing how this resolves and how future additional log lines and such pan out, but it's definitely not a conversation to have now.)

However, counteracting that is that I believe that documentation shouldn't exist alongside code that it's not documenting.

As such, I'm fine with either options 2 or 3.

My concern with 2 is that it may pose an issue inviting someone to the org when all they'll be doing is editing guides.
My concern with 3 is that it's likely that any org for documentation will also include all the members of this org, and I'm not sure if you can set up github permissions to say "this org includes everyone from that org". As such, keeping members/permissions synced between the two may be a bit sketchy/annoying.

**Comment by quisquous** [comment]
> My concern with 2 is that it may pose an issue inviting someone to the org when all they'll be doing is editing guides.

I think that should be fine.  You can set up a separate "docs" team for a hypothetical OverlayPlugin/docs repo that has separate permissions.  Being invited to the org doesn't necessarily give any permissions until they were assigned this new team.

> As such, keeping members/permissions synced between the two may be a bit sketchy/annoying.

Yeah, this is my feeling as well.  Also, I think that having everything under a single organization makes the "vacation factor" a little bit less of a risk too since there's more likely to be somebody who can sort out privileges, than some random one-off repo somewhere else.  The community is already fractured enough and hard to find things that having more places for people to look will only make things harder.

**Comment by quisquous** [comment]
I'll go ahead and do (2) and make a OverlayPlugin/docs repo.

**Comment by quisquous** [comment]
https://github.com/OverlayPlugin/docs
