### ISSUE TITLE
Curl SSL Issues

### ISSUE THREAD

**Issue by quisquous** [OverlayPlugin/OverlayPlugin#140]
This is the conversation in discord that ends here: <https://discord.com/channels/551474815727304704/551892582855344128/1049822282769510411> (with reply chains up)

My conclusion from this is that we could try to fix curl to use the right system trust store, but it'd be better to switch to using `System.Net.Http.HttpClient.GetStringAsync` instead of using curl.  (I don't know why this is using curl in the first place, vs just using built-in C# stuff.  Maybe @valarnin remembers?)

Does anybody see any potential issues to switching to using a different method for fetching files?

**Comment by valarnin** [comment]
I think that using built-in .NET calls will break support for Win7 and earlier due to the `raw.githubusercontent.com` domain only supporting TLS 1.2 and TLS 1.3, but I don't have a win7 VM handy to test with.

As Techno mentioned in Discord as well, this would also need to be checked against Linux.

**Comment by EQAditu** [comment]
ACT has some .NET config changes that are supposed to make even Vista work with TLS1.2 as long as .NET Framework 4.6(.1?) is installed.  It's been a few years since I've tested this and my memory is now fuzzy.

**Comment by quisquous** [comment]
This should be fixed by #186

**Comment by ngld** [comment]
> I don't know why this is using curl in the first place, vs just using built-in C# stuff.

OverlayPlugin was my first real C# project, I've used curl a lot in the past and there were some weird errors related to downloads that I couldn't figure out. Switching to curl significantly reduced the user complaints about failed CefSharp downloads so I kept it.

Curl should always use the right trust store since the `libcurl.dll` should be configured to use schannel (Windows' TLS implementation) just like the `curl.exe` shipped with Windows.

That said, as mentioned above, this is obsolete now.
