### ISSUE TITLE
Copy resource files into output directory

### ISSUE THREAD

**Issue by quisquous** [OverlayPlugin/OverlayPlugin#52]
When building, it would be nice if everything in `OverlayPlugin.core/resources/` ended up in `out/Release/resources/` so that OverlayPlugin dev builds can be loaded directly into ACT without additional manual steps.

This comes up in #49, but is already the case for all the other resources.  Some files *are* copied (e.g. LICENSE/Readme) via post-build xcopy steps.  Maybe there needs to be more or some other solution here.

**Comment by valarnin** [comment]
I think the build process in general needs a thorough passover to clean up things.

For instance, as it stands now, running `build.ps1` will drop you in the `out/Release` folder, so I frequently have to do `cd ..\..; .\build.ps1` to build again.

I'm also not sure why OP needs to build cURL itself instead of using an already-available binary distribution, or offering an option during build to fetch binaries instead of building from source.
