### ISSUE TITLE
Catbot alert and dps meter down?

### ISSUE THREAD

**Issue by Theletha** [OverlayPlugin/OverlayPlugin#57]
Just checking if the catbot raid alerts and the dps meter is down for everyone or if my install is corrupt or if its a browsingway issue? 

Timeline is showing for me and aggro list which is making me unsure since its the first time for me its 50% working.

**Comment by valarnin** [comment]
Any time the game executable is changed by a patch, the FFXIV_ACT_Plugin needs to be updated to support the new version.

As such, usually nothing will work when a new game update comes out. Occasionally, chat log lines will still work, which is what the cactbot timeline is currently based on, because those are read from memory and not from network data.

The FFXIV_ACT_Plugin was updated with a beta earlier today, and an official full release at 6:53PM EST. Please ensure you are running FFXIV_ACT_Plugin version 2.6.6.6 or newer.

**Comment by Theletha** [comment]
i see, thank you for the response
